file-version: 1

# Mensagens do plugin
Mensagens:
  semfaccao: '&cVocê precisa estar em alguma facção para poder utilizar este comando.'
  open: '&cO Jogador @jogador já está com o menu de geradores aberto.'
  contemspawner: '&cVocê não pode desfazer sua facção pois ela ainda possui geradores armazenados.'
  cargo: '&cSeu cargo não permite utilizar do menu de geradores.'

# Delay para salvar os geradores (minutos)
TempoSave: 5

# Cargos que podem acessar o /f geradores
Cargos:
  Oficial: true
  Membro: false
  Recruta: false

# Comando usado para givar o Spawner de volta para o player
# Configure este comando de acordo com seu plugin de spawners
Comando-Para-Devolver-Spawner: "sgive @jogador @tipo @quantia"

######################################################################################
############ { CONFIGURAÇÃO DOS NOMES DOS SPAWNERS PARA GIVAR DE VOLTA } #############
######################################################################################

Tipo-Do-Mob:
  # TIPO_DO_MOB: "nome que você usa pra givar"
  BLAZE: "BLAZE"
  CAVE_SPIDER: "CAVE_SPIDER"
  CHICKEN: "CHICKEN"
  COW: "COW"
  CREEPER: "CREEPER"
  ENDERMAN: "ENDERMAN"
  IRON_GOLEM: "IRON_GOLEM"
  MAGMA_CUBE: "MAGMA_CUBE"
  PIG: "PIG"
  PIG_ZOMBIE: "PIG_ZOMBIE"
  SHEEP: "SHEEP"
  SKELETON: "SKELETON"
  SLIME: "SLIME"
  SPIDER: "SPIDER"
  WITHER: "WITHER"
  ZOMBIE: "ZOMBIE"
  
#----------------
# Diversos plugins de spawner não utilizam o ENTITY_TYPE para gerenciar o tipo do Spawner.
# Alguns plugins usam o ID do mob para gerenciar o tipo do Spawner.
# Outros plugins usam nomes vanilla para gerenciar o tipo do Spawner.

#-----------------
# A configuração atual foi feita usando o ENTITY_TYPE e foi testada no plugin System.

#----------------
# Para facilitar eu já deixei pronta a configuração baseada no ID e baseada no nome vanilla do mob.

# Esta configuração foi feita para os IDs e foi testada no SilkSpawners 5.0 e no TintaSpawner 2.0
# Link: https://pastebin.com/raw/hfdrW2hM

# Esta configuração foi feita para os nomes VANILLA e foi testada no LMobSpawner
# Link: https://pastebin.com/raw/iQQimYG3

#---------------
# Caso você esteja com problemas basta contactar os desenvolvedores!
# Nesta sessão você deve configura qual a identificação do tipo do Spawner.
# Esta identificação sera usada na hora no comando para devolver o Spawner para o jogador.